package com.github.hugovallada.chat.provider

import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class JsonWebTokenProviderTest {

    @Autowired
    private lateinit var tokenProvider: TokenProvider

    @Test
    fun test() {
        val decoded = tokenProvider.decode(
            "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InJhcnpUdGdkUEFOTFgxMkRTU25UMyJ9.eyJnaXZlbl9uYW1lIjoiSHVnbyIsImZhbWlseV9uYW1lIjoiTG9wZXMiLCJuaWNrbmFtZSI6InZhbGxhZGFodWdvIiwibmFtZSI6Ikh1Z28gTG9wZXMiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUdObXl4Wk9jRW9PT0p4cHZRUjNJZ2dHbVRabEJoWHE3ZlJXWGthZ2xPNEs9czk2LWMiLCJsb2NhbGUiOiJwdC1CUiIsInVwZGF0ZWRfYXQiOiIyMDIzLTAzLTExVDE5OjMwOjI4Ljc1MloiLCJlbWFpbCI6InZhbGxhZGFodWdvQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2Rldi1lNHM0eWh3cnJlbm9jM2JuLnVzLmF1dGgwLmNvbS8iLCJhdWQiOiJiOHBYZWs3SFg3S0ZSWjhkMXlveWdUOFdBWE94QUF2cyIsImlhdCI6MTY3ODU2MzAzNSwiZXhwIjoxNjc4NTk5MDM1LCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNzU2NDIyNjU2MzgwNzI0OTQ4MyIsInNpZCI6IjUzalVSYV9zYWlJbmVhNFZqXzZuMUE2cnVrZ2hfM1lEIiwibm9uY2UiOiJhWFpWUTFsV2NUaFRWbk0zUW5SM1ltRm9NRzlvUTJoclJYZHJjV3h2TlZWUk9YNVdSRTFNVkdkUldRPT0ifQ.ZXpIKpwt5JVGJZiC50c3gxiRumuolDP8NDuBzutyK-edhfW5NjlH1B9hx3PYTr5c2uGov4xNRrVuT51BKt69WPHwUzHxF2AluW0PJDf5GF_YRTWGkbICRwX_f46qRqLY-CJehZckZt8QjYa16I5SzdEVqalbUXlO5kkC5SKNX6vl9IrzaVXSOjlJutdcLP4VeE2lTfQHUktJsMGptcJWopiXUNdSMzzZvvO7jHypibvhJH2__sBwJV24UJewg1_xzvFPFz5B3nNVmbcE-nFKv0Hmp-JB8CCFjhnvIgWgDXFeGy6xiDnjVbewKekGZLXomlWII_IrgFBBzxGh5Q0y-w"
        )
        println(decoded)
    }
}